{{- if .Values.carreiraMaisCore.enabled }}
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Values.carreiraMaisCore.name }}
  namespace: {{ .Values.global.namespace }}
data:
  config.json: |
    {
      "featureApi": {
        "baseUri": "/rewards-core/v1",
        "autoDiscoveryFeatures": true,
        "routes": []
      }
    }

{{- end}}