{{- if .Values.carreiraMaisCore.enabled }}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.carreiraMaisCore.name }}
  name: {{ .Values.carreiraMaisCore.name | quote }}
  namespace: {{ .Values.global.namespace | quote }}
spec:
  ports:
    - name: api
      protocol: TCP
      port: {{ .Values.carreiraMaisCore.apiPort }}
      targetPort: {{ .Values.carreiraMaisCore.apiPort }}
  selector:
    app: {{ .Values.carreiraMaisCore.name | quote }}

{{- end }}