apiVersion: v1
appVersion: 0.1.5
description: carreiramais-admin-frontend
keywords:
- carreiramais
maintainers:
- email: infra@carreiramais.app.br
  name: carreiramais-admin-frontend
name: carreiramais-admin-frontend
version: 0.1.5