# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

autoscaling:
  enabled: false
  minReplicas: 3
  maxReplicas: 10
  ## targetCPUUtilizationPercentage only used if the cluster doesn't support autoscaling/v2beta
  targetCPUUtilizationPercentage:
  ## Otherwise for clusters that do support autoscaling/v2beta, use metrics
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80

global:
  clusterDomain: cluster.local
  updateStrategy: "RollingUpdate"
  editor: "CarreiraMais"
  namespace: "carreiramais"
  domainName: "dev.example.com"
  pullPolicy: Always
  imagePullSecrets:
  - name: regsecret

  monitoring:
    datadog:
      enabled: false
      env: env_name
      tennant: client_name
      debug: false

  mongodb:
    shared:
      url: mongodb-shared.dev.example.com:27017
      user: root
      pass: mongodb
#      prefix: mongodb+srv://
      prefix: mongodb://
    local:
      url: mongodb-0.mongodb-headless.carreiramais.svc.cluster.local:27017,mongodb-1.mongodb-headless.carreiramais.svc.cluster.local:27017
      user: root
      pass: mongodb
#      prefix: mongodb+srv://
      prefix: mongodb://

###################
carreiraMaisAdminFrontend:
  enabled: true
  name: carreira-mais-admin-frontend
  updateStrategy: "RollingUpdate"
  image:
    repository: cmaisdockerimages.azurecr.io
    name: carreira-mais-admin-frontend
    tag: ea314af1a06981fcb3a8d89e38a919bbf267a1e5
    pullPolicy: Always

  replicaCount: 1

  apiPort: 3000

  env:
    - name: BACKEND_URI
      value: http://carreira-mais-core.carreiramais.svc.cluster.local:3000

  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: "nginx"
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      nginx.ingress.kubernetes.io/affinity: "cookie"
    hosts:
      - host: client1.admin.carreiramais.app.br
        paths:
          - /
    tls:
     - secretName: client1.admin.carreiramais.app.br
       hosts:
         - client1.admin.carreiramais.app.br


  resources:
    requests:
      cpu: 10m
      memory: 4000Mi
    limits:
      cpu: 1500m
      memory: 4000Mi

  readinessProbe:
    tcpSocket:
      port: 3000
    initialDelaySeconds: 300
    timeoutSeconds: 1
    periodSeconds: 10
    successThreshold: 1
    failureThreshold: 5

  livenessProbe:
    tcpSocket:
      port: 3000
    initialDelaySeconds: 300
    timeoutSeconds: 1
    periodSeconds: 10
    successThreshold: 1
    failureThreshold: 3

  nodeSelector: {}

  tolerations: []

  affinity: {}