{{- if .Values.carreiraMaisWallet.enabled }}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.carreiraMaisWallet.name }}
  name: {{ .Values.carreiraMaisWallet.name | quote }}
  namespace: {{ .Values.global.namespace | quote }}
spec:
  ports:
    - name: api
      protocol: TCP
      port: {{ .Values.carreiraMaisWallet.apiPort }}
      targetPort: {{ .Values.carreiraMaisWallet.apiPort }}
  selector:
    app: {{ .Values.carreiraMaisWallet.name | quote }}

{{- end }}