{{- if .Values.carreiraMaisConfigServer.enabled }}
{{- if .Values.autoscaling.enabled }}
apiVersion: {{ .Capabilities.APIVersions.Has "autoscaling/v2" | ternary "autoscaling/v2" "autoscaling/v1" }}
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.carreiraMaisConfigServer.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.carreiraMaisConfigServer.name }}
  minReplicas: {{ .Values.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.maxReplicas }}
  {{- if not (.Capabilities.APIVersions.Has "autoscaling/v2") }}
  targetCPUUtilizationPercentage: {{ .Values.autoscaling.targetCPUUtilizationPercentage | default 80 }}
  {{- else }}
  metrics:
    {{- toYaml .Values.autoscaling.metrics | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}