{{- if .Values.carreiraMaisConfigServer.ingress.enabled -}}
{{- $fullName := .Values.carreiraMaisConfigServer.name -}}
{{- $svcPort := .Values.carreiraMaisConfigServer.apiPort -}}
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress

metadata:
  name: {{ .Values.carreiraMaisConfigServer.name }}
  {{- with .Values.carreiraMaisConfigServer.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if .Values.carreiraMaisConfigServer.ingress.tls }}
  tls:
  {{- range .Values.carreiraMaisConfigServer.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  {{- range .Values.carreiraMaisConfigServer.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
        - pathType: Prefix
          {{- range .paths }}
          path: {{ . }}
          backend:
            service:
              name: {{ $fullName }}
              port:
                number: {{ $svcPort }}
          {{- end }}
  {{- end }}
{{- end }}
