apiVersion: v1
appVersion: 0.1.0
description: carreiramais-wallet
keywords:
- carreiramais
maintainers:
- email: infra@carreiramais.app.br
  name: carreiramais-wallet
name: carreiramais-wallet
version: 0.1.0